/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'id' : bigint,
  'avatarInitials' : string,
  'name' : string,
  'phone' : string,
}
export interface Conversation {
  'id' : bigint,
  'lastMessageTime' : [] | [Time],
  'messages' : Array<Message>,
  'lastMessage' : [] | [Message],
  'unreadCount' : bigint,
  'contactId' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'timestamp' : Time,
  'senderId' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'markAsRead' : ActorMethod<[bigint], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], Conversation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];