/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'avatarInitials' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
  'senderId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'lastMessageTime' : IDL.Opt(Time),
  'messages' : IDL.Vec(Message),
  'lastMessage' : IDL.Opt(Message),
  'unreadCount' : IDL.Nat,
  'contactId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'markAsRead' : IDL.Func([IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Conversation], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'avatarInitials' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
    'senderId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'lastMessageTime' : IDL.Opt(Time),
    'messages' : IDL.Vec(Message),
    'lastMessage' : IDL.Opt(Message),
    'unreadCount' : IDL.Nat,
    'contactId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'markAsRead' : IDL.Func([IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Conversation], []),
  });
};

export const init = ({ IDL }) => { return []; };